### PR TITLE
revive the package ?

### PR DESCRIPTION
**Pull request by sumiya11**
Hi, this package is amazing! I have made a bit of changes so that it compiles and tests pass without warnings. 

Were there anything else to add to make the package usable? Would you consider releasing a patch then if I fix it?

I may need to factor some polynomials over rationals to solve systems exactly with groebner bases.

ps. I love _Modern Computer Algebra_ too 😄

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks! I'm glad to see this has some use. I always wanted to revisit this, as there have been some changes in the Julia ecosystem that should speed things up here. But getting it running again is awesome. 

You should bump the version number so it can be registered more quickly. I see you bumped the Julia version to 1.7. Was this necessary? If not, we should keep it on 1.6 with its long term support. If necessary, well then it is what it is.

**Comment by sumiya11** [comment]
Bump version. And I reverted to Julia v1.6

**Comment by sumiya11** [comment]
Hi @jverzani , is there something to add here to make this mergeable ?

**Comment by jverzani** [comment]
Hopefully just a reminder ... which I'm thankful for. Let me take care of it next thing.

**Pull request merged**
